name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}] # Обновява се веднъж дневно
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: drnecrotix
          template: terminal # <--- Сменяме шаблона
          base: header, activity, repositories
          config_timezone: Europe/Sofia
          
          # Плъгини за терминален изглед
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: bytes, percentage
